
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: logs
      port: 8081
      targetPort: 8081
    - name: soap
      port: 8082
      targetPort: 8082
  selector:
    app: spring-boot-api
